<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>九宫格</title>
    <style type="text/css">
        .lm{
           float:left;
           padding-bottom: 31%;
           padding-right: 31%;
           border-radius: 10%;
           margin: 1%;
           background-color:orange;
        }
    </style>
</head>
<body>
  <div class="lm"></div>
  <div class="lm"></div>
  <div class="lm"></div>
  <div class="lm"></div>
  <div class="lm"></div>
  <div class="lm"></div>
  <div class="lm"></div>
  <div class="lm"></div>
  <div class="lm"></div>
  </body>
  </html>       
